id = "lumina"
name = "Lumina"
version = "1.0.0"
schema_version = 1
authors = ["Alex Thomson <alexjthomson1882@gmail.com>"]
description = "A theme that's easy on your eyes and your monitor."
repository = "https://github.com/alexjthomson/lumina-zed"
